name: Build library
run-name: Build library by ${{ github.actor }}

on:
  push:
    branches:
      - master
      - test
      - qt-6.8
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
      - test
      - qt-6.8
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: read
  packages: write

env:
  qt_version: 6.8.0
  vlc_run_id: 13025457813
  libvlc_version: mg-2025-08-22

jobs:
  build_linux:
    # note we only build for 24.04 at the moment, library should be binary compatible
    # with 22.04

    name: Build for Linux
    runs-on: [ ubuntu-22.04 ]

    env:
      build_dir: './build'
      install_prefix: '${{ github.workspace }}/install_linux'
      libs_dir: '${{ github.workspace }}/libs_deps'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Get dependency (libvlc)
        uses: robinraju/release-downloader@v1
        with:
          repository: 'MediaGun/vlc'
          tag: ${{ env.libvlc_version }}
          fileName: libvlc4-linux-ubuntu2404.tar.gz
          extract: true
          out-file-path: 'libs_deps'

      - name: Extract VLC
        working-directory: ${{ env.libs_dir }}
        run: |
          mkdir -p ${{ env.libs_dir }}/libvlc && tar -xvf libvlc4-linux-ubuntu2404.tar.gz -C ${{ env.libs_dir }}/libvlc

      - name: Install libs
        run: sudo apt-get install ninja-build

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          dir: ${{ github.workspace }}/qt
          modules: 'qtshadertools'
          tools: 'tools_ninja'

      - name: Configure
        env:
          LIB_DIR: ${{ env.libs_dir }}/libvlc
        run: >-
          cmake -S . -B ${{ env.build_dir }}
          -GNinja
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DCMAKE_INSTALL_PREFIX=${{ env.install_prefix }}

      - name: Build
        run: cmake --build ${{ env.build_dir }}

      - name: Install
        run: cmake --install ${{ env.build_dir }}

      - name: 'Tar files (to preserve symlinks)'
        run: tar -cvf quickvlc.tar -C ${{ env.install_prefix }} .

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: quickvlc-linux
          path: quickvlc.tar

  build_windows:
    name: Build for Windows
    runs-on: [ windows-2022 ]

    env:
      build_dir: './build'
      install_prefix: '${{ github.workspace }}/install_windows'
      libs_dir: '${{ github.workspace }}/libs_deps'
      qt_dir: ${{ github.workspace }}
      qt_tools_dir: ${{ github.workspace }}/Qt/Tools

    steps:
      - run: ls 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC'

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup MSBuild (optional, for VS environment)
        uses: microsoft/setup-msbuild@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          arch: 'win64_msvc2022_64'
          dir: ${{ github.workspace }}
          modules: 'qtshadertools'
          tools: 'tools_ninja'
          add-tools-to-path: true

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Get dependency (libvlc)
        uses: robinraju/release-downloader@v1
        with:
          repository: 'MediaGun/vlc'
          tag: ${{ env.libvlc_version }}
          fileName: 'libvlc4-windows.zip'
          extract: true
          out-file-path: '${{ env.libs_dir }}/libvlc'

      - name: Configure
        env:
          LIB_DIR: ${{ env.libs_dir }}/libvlc/sdk
        run: >-
          cmake -S . -B ${{ env.build_dir }}
          -G "Visual Studio 17 2022" -T v143
          -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX="${{ env.install_prefix }}"
        shell: cmd

      - name: Build
        run: >-
          cmake --build ${{ env.build_dir }} --config Release
        shell: cmd

      - name: Install
        run: >-
          cmake --install ${{ env.build_dir }}
        shell: cmd

      - name: Compress
        run: Compress-Archive -Path ${{ env.install_prefix }}\* -DestinationPath libvlc4-windows.zip

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: quickvlc-windows
          path: libvlc4-windows.zip

  build_macos:
    name: Build for MacOS
    runs-on: [ macos-13 ]

    env:
      build_dir: './build'
      install_prefix: '${{ github.workspace }}/install_macos'
      libs_dir: '${{ github.workspace }}/libs_deps'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Get dependency (libvlc)
        uses: robinraju/release-downloader@v1
        with:
          repository: 'MediaGun/vlc'
          tag: ${{ env.libvlc_version }}
          fileName: 'vlc-macos-sdk-4.0.0-universal-dev.tar.gz'
          extract: true
          out-file-path: 'libs_deps'

      - name: Untar artifacts
        working-directory: ${{ env.libs_dir }}
        run: |
          echo libs_deps
          ls libs_deps || true
          echo current dir
          ls
          echo github.workspace ${{ github.workspace }}
          ls ${{ github.workspace }} || true
          echo env.libs_dir ${{ env.libs_dir }}
          ls ${{ env.libs_dir }} || true
          mkdir ${{ env.libs_dir }}/libvlc && tar -xvf ${{ github.workspace }}/libs_deps/vlc-macos-sdk-4.0.0-universal-dev.tar.gz -C ${{ env.libs_dir }}/libvlc

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          dir: ${{ github.workspace }}/qt
          modules: 'qtshadertools'
          tools: 'tools_ninja'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure
        env:
          LIB_DIR: ${{ env.libs_dir }}/libvlc
        run: |
          cmake -S . -B ${{ env.build_dir }} -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX=${{ env.install_prefix }}

      - name: Build
        run: cmake --build ${{ env.build_dir }}

      - name: Install
        run: cmake --install ${{ env.build_dir }}

      - name: 'Tar files (to preserve symlinks)'
        run: tar -cvf quickvlc.tar -C ${{ env.install_prefix }} .

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: quickvlc-macos
          path: quickvlc.tar

  release:
    if: github.ref_type == 'tag'
    needs: [ build_linux, build_windows, build_macos ]
    runs-on: ubuntu-latest

    steps:
      - name: Download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: quickvlc-linux
          path: ./artifacts/

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: quickvlc-windows
          path: ./artifacts/

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: quickvlc-macos
          path: ./artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
